<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>10.0</LangVersion>
		<TargetFrameworks>net9.0;net8.0;net6.0;net48;net472</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>OpenVinoSharp.Extensions.model.PaddleOCR</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>OpenVINO.CSharp.API.Extensions.PaddleOCR</PackageId>
		<Version>1.0.6-alpha.1</Version>
		<Title>OpenVINO C# API deploy PaddleOCR</Title>
		<Authors>Guojin Yan</Authors>
		<Product>OpenVINO C# API</Product>
		<Company>Guojin Yan</Company>
		<PackageTags>OpenVINO;CSharp;C#;PaddleOCR</PackageTags>
		<Description>Deploy PaddleOCR model using OpenVINO C # API to achieve text image recognition.</Description>
		<PackageIcon>logo.png</PackageIcon>
		<RepositoryUrl>https://github.com/guojin-yan/PaddleOCR-OpenVINO-CSharp.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/guojin-yan/PaddleOCR-OpenVINO-CSharp.git</PackageProjectUrl>
		<PackageOutputPath>../../nuget</PackageOutputPath>
		<NeutralLanguage>zh</NeutralLanguage>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReleaseNotes>
			更新OpenCvSharp4支持4.11，OpenVINO.CSharp.API为2025.0.0.1；
			添加PP-OCRv5支持和一键下载部署
		</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\nuget\logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="itext" Version="9.2.0" />
		<PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
		<PackageReference Include="OpenVINO.CSharp.API" Version="2025.1.0.2" />
		<PackageReference Include="OpenVINO.CSharp.API.Extensions" Version="1.0.3" />
		<PackageReference Include="SharpCompress" Version="0.40.0" />
		<PackageReference Include="Spire.XLS" Version="15.7.8" />
	</ItemGroup>

</Project>
